### ISSUE TITLE
Features should be

### ISSUE THREAD

**Issue by hiennguyen92** [NuclearCMS/Nuclear#1]
the first thank you for cms. is is so great.
however I still feel lack of some functions.
-ROLE: User Normal
-Document on how to use
-Editing UI.

I hope that version 3.0 would be nice from you.

Thanks

**Comment by Hyleeh** [comment]
Hi!

Thank you, I am glad that you liked Nuclear.
The features you mention actually exist:
1. If a user does not have ACCESS_REACTOR or SUPERADMIN permissions, they cannot access the administration panel, so they become a normal user. You can have separate permissions for them if you would like to further limit their behavior in the site.
2. Since Nuclear is a theme based CMS in terms of UI, you can create a new theme in `config/themes.php` for the administration panel. Changing `active_reactor` theme to the new theme that you have created will change administration panel UI.

Since Nuclear is currently being developed only by me I have to first finish the features that I plan to implement to the version 3.0. Then I will start working on documentation.

You should ask if you have any other questions though
