### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by sirajkrm** [NuclearCMS/Nuclear#3]
hi
i'm a network and system administrator
i saw this project " Nuclear "
to be honest.. it's very cool tool for DMS
great design
great capabilities
& great work !
i would like to suggest.. if is it possible
to make this software.. **read/write** the documents uploaded **instead of downloading** them
it would make the software improved in a sophisticated way
i hope that would be in consideration :)
thank's in advance.

**Comment by Hyleeh** [comment]
Hi,

I'm glad that you liked it!

There are options to edit images currently (like cropping, flipping, blurring etc.)
You can access image options near the save button to the below right corner by clicking the button that has the image icon in the image information view.

But it is not quite possible to implement editing options to pdfs or office documents since they require dedicated software

If you have any suggestions that would ease implementation of editing documents you are most welcome to propose:)

Best,

**Comment by sirajkrm** [comment]
hi
thank's for response ^^
ok that's great for editing an image
as i told you.. i'm a network and system administrator
web development isn't my thing and i'm so terribly sorry for that :/
however...
i think with a simple research you can manage to do it
here's this link for reading/writing word with PHP library
https://github.com/PHPOffice/PHPWord
here's this link for managing files etc...
https://github.com/UniSharp/laravel-filemanager-plus

i don't know you saw them already.. but tried to help you with some searching
best of luck dude
thank's.

**Comment by Hyleeh** [comment]
Hey:)

I saw these libraries but they are hard to implement with the current structure of my system
In later phases of the project I may implement such functionality
(or an integration with google documents might be a better choice)

I added this feature to my iteration plan

Thanks and best,
