### ISSUE TITLE
Route API

### ISSUE THREAD

**Issue by hiennguyen92** [NuclearCMS/Nuclear#4]
How I can setup api route? I tried it returns 404

thanks.

**Comment by Hyleeh** [comment]
Hi,

There are multiple ways you can define routes (anything you can do with Laravel is okay basically)

But best place to register them is under routes/site.php (do not change reactor.php)
The filename for route follows the theme, that's why you should use site.php for the site theme.

Reactor theme is for the CMS panel, common should not be changed also install is for installation routes...

If you define a new theme, you should create a routes/theme-name.php file to have the new routes for the theme.

One reason that if you still get 404 when you define routes under site.php is that Nuclear caches routes for optimized performance. So when you define a new route you should either re-cache them or clear the routes cache.

The way you do that is under Maintain Nuclear menu, following screenshots show where that option is

The maintenance menu:
<img width="1440" alt="screen shot 2017-01-22 at 15 40 19" src="https://cloud.githubusercontent.com/assets/5340560/22182562/c74c67ec-e0b0-11e6-9fcc-1cb7c46480b7.png">

Maintenance options:
<img width="1440" alt="screen shot 2017-01-22 at 15 40 24" src="https://cloud.githubusercontent.com/assets/5340560/22182564/d83bebae-e0b0-11e6-863a-fd96add772ef.png">

If you have additional questions, feel free to ask

Best,

**Comment by hiennguyen92** [comment]
Thanks, after I clear the route cache it has been working.

**Comment by Hyleeh** [comment]
No problem:) feel free to ask anything else
